### ISSUE TITLE
Shouldn't option just be an alias?

### ISSUE THREAD

**Issue by RobGThai** [miguelgrinberg/climax#1]
I'm mostly curious about the decision to have `option`  define separately from `argument`. Is there a reason that you prefer this way over simple 

``` python
def argument(*args, **kwargs):
   ...
   return decorator

option = argument
```

**Comment by miguelgrinberg** [comment]
Not really a strong reason, but my way allows you to write documentation for it.

**Comment by RobGThai** [comment]
@miguelgrinberg Thanks, for clarifying.
