### ISSUE TITLE
Support for parser.add_argument_group

### ISSUE THREAD

**Issue by kmatarese** [miguelgrinberg/climax#4]
Hi,

First off thanks for putting this library together. 

I'm using climax in another project, but I'm running into the issue described [here](https://stackoverflow.com/a/57582191/10682164) and would like to try something like the solution in that link which utilizes parser.add_argument_group and then adds arguments to specific groups based on whether they are really required or not. I realize this is not an issue with climax, but an underlying issue with argparse that I'm hoping to work around while still using climax.

From what I can tell in the climax code, since you are calling parser.add_argument directly there might not be a simple way to do this. Passing a custom parser doesn't really solve it, and I also don't think the climax "group" concept is quite the same thing.

I know some would say this is by design in argparse and I should be making required args positional. I don't agree with that as it can negatively impact command line usability/readability.

Any thoughts on how this might be possible with climax would be appreciated. Thanks!

**Comment by miguelgrinberg** [comment]
My recommendation is that you fork this repo and make the necessary changes in your own version of climax, I don't see how this can be changed from the application side.

**Comment by kmatarese** [comment]
OK, I figured that would be the case. Thanks for confirming.
