### ISSUE TITLE
Support custom argparse in regular command like subcommand

### ISSUE THREAD

**Issue by mtyurt** [miguelgrinberg/climax#5]
Hello,

The reason I'm asking for this feature is to add mutually exclusive argument group support to the main command definition. Current subcommand example provides this feature, but to the subcommand, not to the main command. This feature would open more doors and possibilities to the climax's usage.

I may give implementing a try if you approve this feature request.

Thanks for the library, it's a great wrapper!

**Comment by miguelgrinberg** [comment]
When you say "custom argparse" do you mean attaching an argparse instance that you built outside of this package?

**Comment by mtyurt** [comment]
I think yes, that's what I suggest. To be clear, my proposal is to be able to run the following code snippet in the end:

```python
import climax

parser = argparse.ArgumentParser('main.py')
parser.add_argument('--repeat', type=int)
parser.add_argument('name')

@climax.command(parser=parser)
def main(repeat, name):
    pass
```

**Comment by miguelgrinberg** [comment]
Yeah, that sounds good. Happy to accept this as a PR!

**Comment by mtyurt** [comment]
Thank you!

**Comment by mtyurt** [comment]
Do you have a release process? When should I expect to use this feature?

**Comment by miguelgrinberg** [comment]
Release 0.4.0 is out with this change.
